blank_issues_enabled: true
contact_links:
  - name: Timeless Launcher Discussions
    url: https://github.com/c8dhjp4tyv-bit/timeless-launcher/discussions
    about: Please ask for support here before opening an issue.
