blank_issues_enabled: true
contact_links:
  - name: Timeless Launcher Discord Server
    url: https://github.com/c8dhjp4tyv-bit/TimelessLauncher/discussions
    about: Please ask for support here before opening an issue.
